#!/usr/bin/env node

/**
 * Suprema HR Integration Setup Script
 * Helps configure and start the application
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🏢 Suprema HR Integration System Setup\n');

async function question(prompt) {
    return new Promise((resolve) => {
        rl.question(prompt, resolve);
    });
}

async function setupEnvironment() {
    console.log('Setting up environment configuration...\n');

    const config = {};

    // Gateway configuration
    config.GATEWAY_HOST = await question('Gateway Host IP (default: 192.168.1.100): ') || '192.168.1.100';
    config.GATEWAY_PORT = await question('Gateway Port (default: 4000): ') || '4000';
    config.GATEWAY_SSL = (await question('Use SSL for Gateway? (y/n, default: n): ')).toLowerCase() === 'y' ? 'true' : 'false';

    // API configuration
    config.API_PORT = await question('API Server Port (default: 3000): ') || '3000';
    config.CORS_ORIGIN = await question('CORS Origin (default: *): ') || '*';

    // Logging
    config.LOG_LEVEL = await question('Log Level (debug/info/warn/error, default: info): ') || 'info';
    config.LOG_FILE = await question('Log File Path (default: ./logs/application.log): ') || './logs/application.log';

    // Database configuration (MySQL with Prisma)
    console.log('\n📊 Database Configuration (MySQL)');
    const dbHost = await question('MySQL Host (default: localhost): ') || 'localhost';
    const dbPort = await question('MySQL Port (default: 3306): ') || '3306';
    const dbUser = await question('MySQL Username (default: root): ') || 'root';
    const dbPass = await question('MySQL Password: ');
    const dbName = await question('MySQL Database Name (default: suprema_hr): ') || 'suprema_hr';
    
    config.DATABASE_URL = `mysql://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbName}`;

    // Features
    config.MAX_EVENTS = await question('Max Events per Request (default: 1000): ') || '1000';
    config.ENABLE_WEBHOOKS = (await question('Enable HR Webhooks? (y/n, default: n): ')).toLowerCase() === 'y' ? 'true' : 'false';
    config.SEED_INITIAL_DEVICES = (await question('Seed initial device data? (y/n, default: y): ')).toLowerCase() !== 'n' ? 'true' : 'false';
    
    if (config.ENABLE_WEBHOOKS === 'true') {
        config.WEBHOOK_URL = await question('HR System Webhook URL: ') || '';
    }

    return config;
}

function generateEnvFile(config) {
    const envContent = `# Suprema HR Integration Configuration
# Generated by setup script on ${new Date().toISOString()}

# Database Configuration (MySQL with Prisma)
DATABASE_URL="${config.DATABASE_URL}"

# Gateway Configuration
GATEWAY_HOST=${config.GATEWAY_HOST}
GATEWAY_PORT=${config.GATEWAY_PORT}
GATEWAY_SSL=${config.GATEWAY_SSL}

# API Configuration
API_PORT=${config.API_PORT}
CORS_ORIGIN=${config.CORS_ORIGIN}

# Logging Configuration
LOG_LEVEL=${config.LOG_LEVEL}
LOG_FILE=${config.LOG_FILE}

# Features
MAX_EVENTS=${config.MAX_EVENTS}
ENABLE_WEBHOOKS=${config.ENABLE_WEBHOOKS}
${config.WEBHOOK_URL ? `WEBHOOK_URL=${config.WEBHOOK_URL}` : '# WEBHOOK_URL=http://your-hr-system.com/webhooks/suprema'}

# Development
NODE_ENV=development
`;

    fs.writeFileSync('.env', envContent);
    console.log('\n✅ Environment file created: .env');
}

function createDirectories() {
    const dirs = ['logs', 'exports', 'temp', 'data'];
    
    dirs.forEach(dir => {
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
            console.log(`✅ Created directory: ${dir}/`);
        }
    });
}

function checkDependencies() {
    console.log('\nChecking dependencies...');
    
    if (!fs.existsSync('node_modules')) {
        console.log('❌ Dependencies not installed. Please run: npm install');
        return false;
    }
    
    console.log('✅ Dependencies installed');
    return true;
}

function displayStartupInfo(config) {
    console.log(`
🎉 Setup Complete!

Configuration Summary:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Gateway:       ${config.GATEWAY_HOST}:${config.GATEWAY_PORT} (SSL: ${config.GATEWAY_SSL})
API Server:    http://localhost:${config.API_PORT}
Logging:       ${config.LOG_LEVEL} -> ${config.LOG_FILE}
Webhooks:      ${config.ENABLE_WEBHOOKS === 'true' ? 'Enabled' : 'Disabled'}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Next Steps:
1. Start the application:
   npm start
   
2. Check application health:
   curl http://localhost:${config.API_PORT}/health
   
3. View API documentation:
   http://localhost:${config.API_PORT}/api

Quick Test Commands:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Search for devices
curl "http://localhost:${config.API_PORT}/api/devices/search"

# Connect to a device
curl -X POST "http://localhost:${config.API_PORT}/api/devices/connect" \\
     -H "Content-Type: application/json" \\
     -d '{"ip":"192.168.1.101","port":51211,"useSSL":false}'

# Get device info
curl "http://localhost:${config.API_PORT}/api/devices/{deviceId}/info"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

For detailed documentation, see README.md

Happy integrating! 🚀
`);
}

async function main() {
    try {
        // Check if .env already exists
        if (fs.existsSync('.env')) {
            const overwrite = await question('.env file already exists. Overwrite? (y/n): ');
            if (overwrite.toLowerCase() !== 'y') {
                console.log('Setup cancelled.');
                rl.close();
                return;
            }
        }

        // Setup environment
        const config = await setupEnvironment();
        
        // Generate .env file
        generateEnvFile(config);
        
        // Create directories
        createDirectories();
        
        // Check dependencies
        const depsOk = checkDependencies();
        
        // Display startup information
        displayStartupInfo(config);
        
        if (!depsOk) {
            console.log('\n⚠️  Please install dependencies before starting the application.');
        }

    } catch (error) {
        console.error('Setup failed:', error.message);
    } finally {
        rl.close();
    }
}

// Run setup if called directly
if (require.main === module) {
    main();
}

module.exports = { main };