/**
 * Suprema Event Monitoring Service
 * Handles real-time event monitoring, event log retrieval, and event processing
 */

import { EventEmitter } from 'events';
import winston from 'winston';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

// Create require function for CommonJS modules
const require = createRequire(import.meta.url);
import fs from 'fs';
import path from 'path';

// Import protobuf services (these would come from the G-SDK)
// These are CommonJS modules generated by protoc
const eventService = require('../../biostar/service/event_grpc_pb');
const eventMessage = require('../../biostar/service/event_pb');

class SupremaEventService extends EventEmitter {
    constructor(connectionService) {
        super();
        this.connectionService = connectionService;
        this.eventClient = null;
        this.eventSubscriptions = new Map(); // deviceId -> subscription
        this.eventCodeMap = new Map();
        this.isMonitoring = false;
        
        this.logger = winston.createLogger({
            level: 'info',
            format: winston.format.combine(
                winston.format.timestamp(),
                winston.format.json()
            ),
            transports: [
                new winston.transports.Console(),
                new winston.transports.File({ filename: 'logs/event-service.log' })
            ]
        });

        this.initializeClient();
        this.loadEventCodeMap();
    }

    /**
     * Initialize event service client
     */
    initializeClient() {
        const gatewayAddress = this.connectionService.getGatewayAddress();
        const credentials = this.connectionService.sslCreds;
        const clientOptions = this.connectionService.getGatewayClientOptions();

        this.eventClient = new eventService.EventClient(gatewayAddress, credentials, clientOptions);
        this.logger.info('Event service client initialized');
    }

    /**
     * Load event code map for event description lookup
     * @param {string} codeMapFile - Path to event code map JSON file
     */
    loadEventCodeMap(codeMapFile) {
        const moduleDir = path.dirname(fileURLToPath(import.meta.url));
        const defaultPath = path.resolve(moduleDir, '..', '..', 'data', 'event_code.json');
        const filePath = codeMapFile || defaultPath;
        try {
            if (fs.existsSync(filePath)) {
                const jsonData = fs.readFileSync(filePath, 'utf8');
                const codeMapData = JSON.parse(jsonData);

                this.eventCodeMap.clear();
                
                codeMapData.entries.forEach(entry => {
                    const key = `${entry.event_code}_${entry.sub_code}`;
                    this.eventCodeMap.set(key, entry.desc);
                });

                this.logger.info(`Loaded ${this.eventCodeMap.size} event code mappings`);
            } else {
                this.logger.warn(`Event code map file not found: ${filePath}`);
                this.createDefaultEventCodeMap();
            }
        } catch (error) {
            this.logger.error('Error loading event code map:', error);
            this.createDefaultEventCodeMap();
        }
    }

    /**
     * Create default event code map with comprehensive Suprema event types
     */
    createDefaultEventCodeMap() {
        const defaultEvents = [
            { event_code: 0x1000, sub_code: 0x0, desc: 'Verify Success' },
            { event_code: 0x1100, sub_code: 0x0, desc: 'Verify Fail' },
            { event_code: 0x1200, sub_code: 0x0, desc: 'Verify Success (Duress)' },
            { event_code: 0x1300, sub_code: 0x0, desc: 'Identify Success' },
            { event_code: 0x1400, sub_code: 0x0, desc: 'Identify Fail' },
            { event_code: 0x1500, sub_code: 0x0, desc: 'Identify Success (Duress)' },
            { event_code: 0x1600, sub_code: 0x0, desc: 'Dual Auth Success' },
            { event_code: 0x1700, sub_code: 0x0, desc: 'Dual Auth Fail' },
            { event_code: 0x1800, sub_code: 0x0, desc: 'Auth Failed (Unregistered)' },
            { event_code: 0x1900, sub_code: 0x0, desc: 'Access Denied' },

            { event_code: 0x2000, sub_code: 0x0, desc: 'User Enrollment Success' },
            { event_code: 0x2100, sub_code: 0x0, desc: 'User Enrollment Fail' },
            { event_code: 0x2200, sub_code: 0x0, desc: 'User Update Success' },
            { event_code: 0x2300, sub_code: 0x0, desc: 'User Update Fail' },
            { event_code: 0x2400, sub_code: 0x0, desc: 'User Delete Success' },
            { event_code: 0x2500, sub_code: 0x0, desc: 'User Delete Fail' },
            { event_code: 0x2600, sub_code: 0x0, desc: 'Delete All User Success' },
            { event_code: 0x2800, sub_code: 0x0, desc: 'Duplicate Credential' },

            { event_code: 0x3000, sub_code: 0x0, desc: 'System Reset' },
            { event_code: 0x3100, sub_code: 0x0, desc: 'System Started' },
            { event_code: 0x3200, sub_code: 0x0, desc: 'System Time Set' },
            { event_code: 0x3201, sub_code: 0x0, desc: 'Timezone Changed' },
            { event_code: 0x3202, sub_code: 0x0, desc: 'DST Changed' },
            { event_code: 0x3300, sub_code: 0x0, desc: 'LAN Connected' },
            { event_code: 0x3400, sub_code: 0x0, desc: 'LAN Disconnected' },
            { event_code: 0x3B00, sub_code: 0x0, desc: 'TCP Connected' },
            { event_code: 0x3C00, sub_code: 0x0, desc: 'TCP Disconnected' },
            { event_code: 0x3F00, sub_code: 0x0, desc: 'Input Detected' },
            { event_code: 0x4000, sub_code: 0x0, desc: 'Tamper On' },
            { event_code: 0x4100, sub_code: 0x0, desc: 'Tamper Off' },
            { event_code: 0x4200, sub_code: 0x0, desc: 'Event Log Cleared' },
            { event_code: 0x4300, sub_code: 0x0, desc: 'Firmware Upgraded' },

            { event_code: 0x5000, sub_code: 0x0, desc: 'Door Unlocked' },
            { event_code: 0x5100, sub_code: 0x0, desc: 'Door Locked' },
            { event_code: 0x5200, sub_code: 0x0, desc: 'Door Opened' },
            { event_code: 0x5300, sub_code: 0x0, desc: 'Door Closed' },
            { event_code: 0x5400, sub_code: 0x0, desc: 'Door Forced Open' },
            { event_code: 0x5500, sub_code: 0x0, desc: 'Door Held Open' },
            { event_code: 0x5600, sub_code: 0x0, desc: 'Forced Open Alarm' },
            { event_code: 0x5700, sub_code: 0x0, desc: 'Forced Open Alarm Cleared' },
            { event_code: 0x5800, sub_code: 0x0, desc: 'Held Open Alarm' },
            { event_code: 0x5900, sub_code: 0x0, desc: 'Held Open Alarm Cleared' },
            { event_code: 0x5C00, sub_code: 0x0, desc: 'Door Release' },
            { event_code: 0x5D00, sub_code: 0x0, desc: 'Lock Door' },
            { event_code: 0x5E00, sub_code: 0x0, desc: 'Unlock Door' },

            { event_code: 0x6000, sub_code: 0x0, desc: 'APB Zone Violated' },
            { event_code: 0x6100, sub_code: 0x0, desc: 'APB Zone Alarm' },
            { event_code: 0x6200, sub_code: 0x0, desc: 'APB Zone Alarm Cleared' },
            { event_code: 0x6300, sub_code: 0x0, desc: 'Timed APB Zone Violated' },
            { event_code: 0x6600, sub_code: 0x0, desc: 'Fire Alarm Input' },
            { event_code: 0x6700, sub_code: 0x0, desc: 'Fire Alarm' },
            { event_code: 0x6800, sub_code: 0x0, desc: 'Fire Alarm Cleared' },

            { event_code: 0x7000, sub_code: 0x0, desc: 'Floor Activated' },
            { event_code: 0x7100, sub_code: 0x0, desc: 'Floor Deactivated' },
            { event_code: 0x7200, sub_code: 0x0, desc: 'Floor Released' }
        ];

        this.eventCodeMap.clear();
        defaultEvents.forEach(event => {
            const key = `${event.event_code}_${event.sub_code}`;
            this.eventCodeMap.set(key, event.desc);
        });

        this.logger.info(`Created default event code map with ${defaultEvents.length} entries`);
    }

    /**
     * Get event description from event codes
     * @param {number} eventCode - Event code
     * @param {number} subCode - Sub code
     * @returns {string} Event description
     */
    getEventDescription(eventCode, subCode) {
        // First try exact match with subcode
        const key = `${eventCode}_${subCode}`;
        if (this.eventCodeMap.has(key)) {
            return this.eventCodeMap.get(key);
        }
        
        // Try with subcode 0 (most events use 0 subcode)
        const baseKey = `${eventCode}_0`;
        if (this.eventCodeMap.has(baseKey)) {
            return this.eventCodeMap.get(baseKey);
        }
        
        // Generate descriptive fallback based on event type ranges
        const hexCode = eventCode.toString(16).toUpperCase().padStart(4, '0');
        
        if (eventCode >= 0x1000 && eventCode < 0x2000) {
            return `Authentication Event (0x${hexCode})`;
        } else if (eventCode >= 0x2000 && eventCode < 0x3000) {
            return `User Event (0x${hexCode})`;
        } else if (eventCode >= 0x3000 && eventCode < 0x5000) {
            return `System Event (0x${hexCode})`;
        } else if (eventCode >= 0x5000 && eventCode < 0x6000) {
            return `Door Event (0x${hexCode})`;
        } else if (eventCode >= 0x6000 && eventCode < 0x7000) {
            return `Zone Event (0x${hexCode})`;
        } else if (eventCode >= 0x7000 && eventCode < 0x8000) {
            return `Lift Event (0x${hexCode})`;
        } else if (eventCode >= 0x9000 && eventCode < 0xA000) {
            return `Intrusion Event (0x${hexCode})`;
        }
        
        return `Event (0x${hexCode})`;
    }

    isAuthenticationEvent(eventCode) {
        const code = Number(eventCode ?? 0);
        return code >= 0x1000 && code < 0x2000;
    }

    isTnaEvent(event) {
        const code = Number(event?.eventcode ?? event?.eventCode ?? 0);
        const tnaKey = Number(
            event?.tnakey
            ?? event?.tnaKey
            ?? event?.rawData?.tnakey
            ?? event?.rawData?.tnaKey
            ?? 0
        );

        return this.isAuthenticationEvent(code) && tnaKey > 0;
    }

    // ================ REAL-TIME MONITORING ================

    /**
     * Enable monitoring for a device
     * @param {string} deviceId - Device ID
     * @returns {Promise<boolean>} Success status
     */
    async enableMonitoring(deviceId) {
        try {
            const req = new eventMessage.EnableMonitoringRequest();
            req.setDeviceid(deviceId);

            return new Promise((resolve, reject) => {
                this.eventClient.enableMonitoring(req, (err, response) => {
                    if (err) {
                        this.logger.error(`Failed to enable monitoring for device ${deviceId}:`, err);
                        reject(err);
                        return;
                    }

                    this.logger.info(`Monitoring enabled for device ${deviceId}`);
                    this.emit('monitoring:enabled', { deviceId });
                    resolve(true);
                });
            });
        } catch (error) {
            this.logger.error('Error enabling monitoring:', error);
            throw error;
        }
    }

    /**
     * Disable monitoring for a device
     * @param {string} deviceId - Device ID
     * @returns {Promise<boolean>} Success status
     */
    async disableMonitoring(deviceId) {
        try {
            const req = new eventMessage.DisableMonitoringRequest();
            req.setDeviceid(deviceId);

            return new Promise((resolve, reject) => {
                this.eventClient.disableMonitoring(req, (err, response) => {
                    if (err) {
                        this.logger.error(`Failed to disable monitoring for device ${deviceId}:`, err);
                        reject(err);
                        return;
                    }

                    // Remove device from tracking map.
                    // Do NOT cancel the shared gRPC stream here — it is shared across all
                    // monitored devices and is only torn down in stopMonitoring().
                    this.eventSubscriptions.delete(deviceId);

                    this.logger.info(`Monitoring disabled for device ${deviceId}`);
                    this.emit('monitoring:disabled', { deviceId });
                    resolve(true);
                });
            });
        } catch (error) {
            this.logger.error('Error disabling monitoring:', error);
            throw error;
        }
    }

    /**
     * Subscribe to real-time events
     * @param {number} queueSize - Event queue size
     * @param {Array} deviceIds - Device IDs to monitor (optional, for filtering)
     * @returns {Object} Event subscription
     */
    subscribeToEvents(queueSize = 100, deviceIds = null) {
        try {
            const req = new eventMessage.SubscribeRealtimeLogRequest();
            req.setQueuesize(queueSize);

            const subscription = this.eventClient.subscribeRealtimeLog(req);

            subscription.on('data', (eventData) => {
                const event = eventData.toObject();
                
                // Filter by device IDs if specified (normalize to string — protobuf returns numbers)
                if (deviceIds && !deviceIds.map(String).includes(String(event.deviceid))) {
                    return;
                }

                // Enhance event with description
                const enhancedEvent = this.enhanceEvent(event);
                
                this.logger.info('Real-time event received:', enhancedEvent);
                this.emit('event:received', enhancedEvent);
                
                // Emit specific event types
                this.emitSpecificEventTypes(enhancedEvent);
            });

            const handleStreamDropped = () => {
                this.isMonitoring = false;
                const currentDevices = Array.from(this.eventSubscriptions.keys());
                if (currentDevices.length > 0) {
                    this.logger.info(`Scheduling auto-reconnect of real-time events for ${currentDevices.length} devices...`);

                    const attemptReconnect = () => {
                        if (this.isMonitoring) return; // already reconnected somewhere else
                        this.startMonitoring(currentDevices, queueSize).catch((e) => {
                            this.logger.error(`Event stream auto-reconnect failed: ${e.message}. Retrying in 10s...`);
                            setTimeout(attemptReconnect, 10000);
                        });
                    };
                    
                    setTimeout(attemptReconnect, 5000);
                }
            };

            subscription.on('end', () => {
                this.logger.info('Event subscription ended');
                this.emit('subscription:ended');
                handleStreamDropped();
            });

            subscription.on('error', (err) => {
                if (err.details === 'Cancelled') {
                    this.logger.info('Event subscription cancelled');
                    this.emit('subscription:cancelled');
                    this.isMonitoring = false;
                } else {
                    this.logger.error('Event subscription error:', err);
                    this.emit('subscription:error', err);
                    handleStreamDropped();
                }
            });

            this.isMonitoring = true;
            this.logger.info('Subscribed to real-time events');
            this.emit('subscription:started', { queueSize, deviceIds });

            return subscription;
        } catch (error) {
            this.logger.error('Error subscribing to events:', error);
            throw error;
        }
    }

    /**
     * Start monitoring multiple devices
     * @param {Array} deviceIds - Array of device IDs to monitor
     * @param {number} queueSize - Event queue size
     * @returns {Promise<Object>} Subscription object
     */
    async startMonitoring(deviceIds, queueSize = 100) {
        try {
            // Enable monitoring for all devices
            for (const deviceId of deviceIds) {
                await this.enableMonitoring(deviceId);
            }

            // Subscribe to events
            const subscription = this.subscribeToEvents(queueSize, deviceIds);
            
            // Store subscription reference
            deviceIds.forEach(deviceId => {
                this.eventSubscriptions.set(deviceId, subscription);
            });

            this.logger.info(`Started monitoring ${deviceIds.length} devices`);
            return subscription;
        } catch (error) {
            this.logger.error('Error starting monitoring:', error);
            throw error;
        }
    }

    /**
     * Stop monitoring for all devices
     * @returns {Promise<boolean>} Success status
     */
    async stopMonitoring() {
        try {
            const deviceIds = Array.from(this.eventSubscriptions.keys());
            
            for (const deviceId of deviceIds) {
                await this.disableMonitoring(deviceId);
            }

            this.isMonitoring = false;
            this.logger.info('Stopped monitoring all devices');
            this.emit('monitoring:stopped');
            
            return true;
        } catch (error) {
            this.logger.error('Error stopping monitoring:', error);
            throw error;
        }
    }

    // ================ EVENT LOG RETRIEVAL ================

    /**
     * Get event logs from device
     * @param {string} deviceId - Device ID
     * @param {number} startEventId - Starting event ID
     * @param {number} maxEvents - Maximum number of events to retrieve
     * @returns {Promise<Array>} Array of events
     */
    async getEventLogs(deviceId, startEventId = 0, maxEvents = 1000) {
        try {
            const req = new eventMessage.GetLogRequest();
            req.setDeviceid(deviceId);
            req.setStarteventid(startEventId);
            req.setMaxnumoflog(maxEvents);

            return new Promise((resolve, reject) => {
                this.eventClient.getLog(req, (err, response) => {
                    if (err) {
                        this.logger.error(`Failed to get event logs for device ${deviceId}:`, err);
                        reject(err);
                        return;
                    }

                    const events = response.toObject().eventsList;
                    const enhancedEvents = events.map(event => this.enhanceEvent(event));
                    
                    this.logger.info(`Retrieved ${enhancedEvents.length} events from device ${deviceId}`);
                    resolve(enhancedEvents);
                });
            });
        } catch (error) {
            this.logger.error('Error getting event logs:', error);
            throw error;
        }
    }

    /**
     * Get image logs from device (for devices that support image logging)
     * @param {string} deviceId - Device ID
     * @param {number} startEventId - Starting event ID
     * @param {number} maxEvents - Maximum number of events to retrieve
     * @returns {Promise<Array>} Array of image events
     */
    async getImageLogs(deviceId, startEventId = 0, maxEvents = 100) {
        try {
            const req = new eventMessage.GetImageLogRequest();
            req.setDeviceid(deviceId);
            req.setStarteventid(startEventId);
            req.setMaxnumoflog(maxEvents);

            return new Promise((resolve, reject) => {
                this.eventClient.getImageLog(req, (err, response) => {
                    if (err) {
                        this.logger.error(`Failed to get image logs for device ${deviceId}:`, err);
                        reject(err);
                        return;
                    }

                    const imageEvents = response.toObject().imageEventsList;
                    this.logger.info(`Retrieved ${imageEvents.length} image events from device ${deviceId}`);
                    resolve(imageEvents);
                });
            });
        } catch (error) {
            this.logger.error('Error getting image logs:', error);
            throw error;
        }
    }

    /**
     * Get filtered event logs
     * @param {string} deviceId - Device ID
     * @param {Object} filters - Event filters
     * @returns {Promise<Array>} Filtered events
     */
    async getFilteredEventLogs(deviceId, filters = {}) {
        try {
            const startEventId = filters.startEventId || 0;
            const maxEvents = filters.maxEvents || 1000;
            
            const events = await this.getEventLogs(deviceId, startEventId, maxEvents);
            
            let filteredEvents = events;

            // Filter by event codes
            if (filters.eventCodes && filters.eventCodes.length > 0) {
                const codes = filters.eventCodes.map(c => parseInt(c));
                filteredEvents = filteredEvents.filter(event => 
                    codes.includes(event.eventcode));
            }

            // Filter by event type (authentication, door, zone, etc.)
            if (filters.eventType) {
                filteredEvents = filteredEvents.filter(event => 
                    event.eventType === filters.eventType);
            }

            // Filter by user IDs
            if (filters.userIds && filters.userIds.length > 0) {
                filteredEvents = filteredEvents.filter(event => 
                    filters.userIds.includes(event.userid));
            }
            
            // Filter by specific user ID
            if (filters.userId) {
                filteredEvents = filteredEvents.filter(event => 
                    event.userid === filters.userId);
            }

            // Filter by date range — event.timestamp is an ISO string set by enhanceEvent()
            if (filters.startDate || filters.endDate) {
                const startDate = filters.startDate ? new Date(filters.startDate) : null;
                const endDate   = filters.endDate   ? new Date(filters.endDate)   : null;
                filteredEvents = filteredEvents.filter(event => {
                    if (!event.timestamp) return false;
                    const eventDate = new Date(event.timestamp);
                    if (isNaN(eventDate.getTime())) return false;
                    if (startDate && eventDate < startDate) return false;
                    if (endDate   && eventDate > endDate)   return false;
                    return true;
                });
            }
            
            // Filter by door ID
            if (filters.doorId !== undefined) {
                filteredEvents = filteredEvents.filter(event => 
                    event.doorid === parseInt(filters.doorId));
            }
            
            // Filter by success/failure for authentication events
            if (filters.authResult !== undefined) {
                const successCodes = [0x1000, 0x1100, 0x1200, 0x1300, 0x1400, 0x1500, 0x1600, 0x1700];
                const failCodes = [
                    0x1001, 0x1002, 0x1003,
                    0x1101, 0x1102, 0x1103,
                    0x1201, 0x1202, 0x1203,
                    0x1301, 0x1302, 0x1303,
                    0x1401, 0x1402, 0x1403,
                    0x1501, 0x1502,
                ];
                
                if (filters.authResult === 'success') {
                    filteredEvents = filteredEvents.filter(event => 
                        successCodes.includes(event.eventcode));
                } else if (filters.authResult === 'fail') {
                    filteredEvents = filteredEvents.filter(event => 
                        failCodes.includes(event.eventcode));
                }
            }

            this.logger.info(`Filtered ${filteredEvents.length} events from ${events.length} total events`);
            return filteredEvents;
        } catch (error) {
            this.logger.error('Error getting filtered event logs:', error);
            throw error;
        }
    }
    
    /**
     * Get historical events with pagination
     * @param {string} deviceId - Device ID
     * @param {Object} options - Pagination and filter options
     * @returns {Promise<Object>} Events with pagination info
     */
    async getHistoricalEvents(deviceId, options = {}) {
        try {
            const page = options.page || 1;
            const pageSize = options.pageSize || 50;
            const startEventId = options.startEventId || 0;
            
            // Fetch more events than needed for pagination
            const fetchSize = Math.max(pageSize * page + 100, 1000);
            
            let events = await this.getEventLogs(deviceId, startEventId, fetchSize);
            
            // Apply filters if provided
            if (options.filters) {
                events = await this.applyFilters(events, options.filters);
            }
            
            // Calculate pagination
            const totalEvents = events.length;
            const totalPages = Math.ceil(totalEvents / pageSize);
            const startIndex = (page - 1) * pageSize;
            const endIndex = startIndex + pageSize;
            
            const paginatedEvents = events.slice(startIndex, endIndex);
            
            return {
                events: paginatedEvents,
                pagination: {
                    page,
                    pageSize,
                    totalEvents,
                    totalPages,
                    hasNextPage: page < totalPages,
                    hasPrevPage: page > 1
                }
            };
        } catch (error) {
            this.logger.error('Error getting historical events:', error);
            throw error;
        }
    }
    
    /**
     * Apply filters to events array
     * @param {Array} events - Events array
     * @param {Object} filters - Filter criteria
     * @returns {Array} Filtered events
     */
    applyFilters(events, filters) {
        let result = [...events];
        
        if (filters.eventType) {
            result = result.filter(e => e.eventType === filters.eventType);
        }
        
        if (filters.userId) {
            result = result.filter(e => e.userid === filters.userId);
        }
        
        if (filters.doorId !== undefined) {
            result = result.filter(e => e.doorid === parseInt(filters.doorId));
        }
        
        if (filters.startDate) {
            const startDate = new Date(filters.startDate);
            result = result.filter(e => e.timestamp && new Date(e.timestamp) >= startDate);
        }
        
        if (filters.endDate) {
            const endDate = new Date(filters.endDate);
            result = result.filter(e => e.timestamp && new Date(e.timestamp) <= endDate);
        }
        
        if (filters.eventCodes && filters.eventCodes.length > 0) {
            const codes = filters.eventCodes.map(c => parseInt(c));
            result = result.filter(e => codes.includes(e.eventcode));
        }
        
        return result;
    }
    
    /**
     * Get events by user ID
     * @param {string} deviceId - Device ID
     * @param {string} userId - User ID to filter
     * @param {number} maxEvents - Maximum events to retrieve
     * @returns {Promise<Array>} User's events
     */
    async getEventsByUser(deviceId, userId, maxEvents = 500) {
        try {
            const events = await this.getEventLogs(deviceId, 0, maxEvents);
            return events.filter(e => e.userid === userId);
        } catch (error) {
            this.logger.error(`Error getting events for user ${userId}:`, error);
            throw error;
        }
    }
    
    /**
     * Get recent authentication events
     * @param {string} deviceId - Device ID
     * @param {number} maxEvents - Maximum events
     * @returns {Promise<Array>} Authentication events
     */
    async getAuthenticationEvents(deviceId, maxEvents = 100) {
        try {
            const events = await this.getEventLogs(deviceId, 0, maxEvents);
            return events.filter(e => e.eventType === 'authentication');
        } catch (error) {
            this.logger.error('Error getting authentication events:', error);
            throw error;
        }
    }
    
    /**
     * Get door events
     * @param {string} deviceId - Device ID
     * @param {number} doorId - Door ID (optional)
     * @param {number} maxEvents - Maximum events
     * @returns {Promise<Array>} Door events
     */
    async getDoorEvents(deviceId, doorId = null, maxEvents = 100) {
        try {
            const events = await this.getEventLogs(deviceId, 0, maxEvents);
            let doorEvents = events.filter(e => e.eventType === 'door');
            
            if (doorId !== null) {
                doorEvents = doorEvents.filter(e => e.doorid === parseInt(doorId));
            }
            
            return doorEvents;
        } catch (error) {
            this.logger.error('Error getting door events:', error);
            throw error;
        }
    }

    // ================ EVENT PROCESSING ================

    /**
     * Enhance event with additional information
     * @param {Object} event - Raw event object
     * @returns {Object} Enhanced event object
     */
    enhanceEvent(event) {
        const enhanced = { ...event };

        // Normalize TNA key (proto: tna.Key TNAKey = 8 on EventLog). After
        // .toObject() the field is `tnakey` and is an integer in [0, 16] where
        // 0 means "no T&A key selected". Per Suprema, the key only denotes a
        // T&A record on authentication events; fixed-TNA mode may still stamp a
        // key on non-auth records such as user-enrollment logs.
        enhanced.tnakey = Number.isInteger(event.tnakey) ? event.tnakey : 0;

        // Add event description
        enhanced.description = this.getEventDescription(event.eventcode, event.subcode);
        
        // Add readable timestamp - the protobuf field is 'timestamp' not 'datetime'
        // It's a Unix timestamp in seconds (UTC)
        try {
            // Check for timestamp field (protobuf uses 'timestamp')
            const rawTimestamp = event.timestamp || event.datetime;
            if (rawTimestamp && rawTimestamp > 0) {
                // Handle both seconds and milliseconds timestamps
                const timestampMs = rawTimestamp > 1e12 ? rawTimestamp : rawTimestamp * 1000;
                const date = new Date(timestampMs);
                if (!isNaN(date.getTime()) && date.getFullYear() > 1970) {
                    enhanced.timestamp = date.toISOString();
                } else {
                    enhanced.timestamp = null;
                }
            } else {
                enhanced.timestamp = null;
            }
        } catch (err) {
            this.logger.warn('Error parsing event timestamp:', err.message);
            enhanced.timestamp = null;
        }
        
        // Add event type classification — if a TNA key was selected, the event
        // is a T&A event ONLY when the underlying authentication code is in the
        // 0x1xxx range (per Suprema EventLog spec, TNAKey rides along on the
        // realtime stream for any auth event).
        enhanced.eventType = this.isTnaEvent(event)
            ? 'attendance'
            : this.classifyEventType(event.eventcode);
        
        // Add severity level
        enhanced.severity = this.getEventSeverity(event.eventcode, event.subcode);

        return enhanced;
    }

    /**
     * Classify event type based on event code
     * @param {number} eventCode - Event code
     * @returns {string} Event type
     */
    classifyEventType(eventCode) {
        if (eventCode >= 0x1000 && eventCode < 0x2000) return 'authentication';
        if (eventCode >= 0x2000 && eventCode < 0x3000) return 'user';
        if (eventCode >= 0x3000 && eventCode < 0x5000) return 'system';
        if (eventCode >= 0x5000 && eventCode < 0x6000) return 'door';
        if (eventCode >= 0x6000 && eventCode < 0x7000) return 'zone';
        if (eventCode >= 0x7000 && eventCode < 0x8000) return 'lift';
        if (eventCode >= 0x9000 && eventCode < 0xA000) return 'zone';
        return 'other';
    }

    /**
     * Get event severity level
     * @param {number} eventCode - Event code
     * @param {number} subCode - Sub code
     * @returns {string} Severity level
     */
    getEventSeverity(eventCode, subCode) {
        const AUTH_SUCCESS_CODES = [0x1000, 0x1100, 0x1200, 0x1300, 0x1400, 0x1500, 0x1600, 0x1700];

        // Authentication failures → warning
        if (eventCode >= 0x1000 && eventCode < 0x2000 && !AUTH_SUCCESS_CODES.includes(eventCode)) return 'warning';

        // Door events — escalate security-critical states
        if (eventCode === 0x2200) return 'error';   // Emergency Lock
        if (eventCode === 0x2201) return 'warning'; // Emergency Unlock
        if (eventCode === 0x2004) return 'warning'; // Door Forced Open
        if (eventCode === 0x2006) return 'warning'; // Door Open Alarm
        if (eventCode === 0x2007) return 'warning'; // Door Open Warning

        // Zone events — scheduled operations are routine; alarms/violations are errors
        if (eventCode === 0x3300) return 'error';                         // Zone Fire Alarm
        if (eventCode === 0x3400 || eventCode === 0x3500) return 'info';  // Zone Scheduled Lock/Unlock
        if (eventCode >= 0x3000 && eventCode < 0x4000) return 'error';   // Other zone violations

        // System events
        if (eventCode === 0x4001) return 'warning'; // Device stopped
        if (eventCode === 0x4300) return 'warning'; // Tamper On
        if (eventCode === 0x4602) return 'error';   // Firmware Update Failed

        return 'info';
    }

    /**
     * Emit specific event types for easier handling
     * @param {Object} event - Enhanced event object
     */
    emitSpecificEventTypes(event) {
        // Emit based on event type
        this.emit(`event:${event.eventType}`, event);
        
        // Emit specific authentication events
        const AUTH_SUCCESS = [0x1000, 0x1100, 0x1200, 0x1300, 0x1400, 0x1500, 0x1600, 0x1700];
        if (AUTH_SUCCESS.includes(event.eventcode)) this.emit('auth:success', event);
        if (event.eventType === 'authentication' && !AUTH_SUCCESS.includes(event.eventcode)) this.emit('auth:failure', event);
        
        // Emit door events
        if (event.eventcode === 0x2000) this.emit('door:opened', event);
        if (event.eventcode === 0x2001) this.emit('door:closed', event);
        if (event.eventcode === 0x2002) this.emit('door:locked', event);
        if (event.eventcode === 0x2003) this.emit('door:unlocked', event);
        
        // Emit attendance/T&A events. Two triggers per Suprema spec:
        //   1. event.tnakey > 0     — any auth event with a T&A key selected
        //   2. eventcode 0x6000-0x6FFF — explicit attendance event codes
        const isTnaKeyEvent = event.tnakey > 0;
        const isAttendanceCode = event.eventcode >= 0x6000 && event.eventcode < 0x7000;
        if (event.eventType === 'attendance' || isTnaKeyEvent || isAttendanceCode) {
            this.emit('attendance:event', event);
            if (isTnaKeyEvent) this.emit(`attendance:key:${event.tnakey}`, event);
            if (event.eventcode === 0x6000) this.emit('attendance:checkin', event);
            if (event.eventcode === 0x6001) this.emit('attendance:checkout', event);
            if (event.eventcode === 0x6002) this.emit('attendance:break_start', event);
            if (event.eventcode === 0x6003) this.emit('attendance:break_end', event);
        }
        
        // Emit system events
        if (event.eventcode === 0x4000) this.emit('system:started', event);
        if (event.eventcode === 0x4001) this.emit('system:stopped', event);
        
        // Emit user management events
        if (event.eventcode === 0x5000) this.emit('user:enrolled', event);
        if (event.eventcode === 0x5001) this.emit('user:deleted', event);
    }

    // ================ EVENT ANALYTICS ================

    /**
     * Get event statistics for a device
     * @param {string} deviceId - Device ID
     * @param {Object} timeRange - Time range for statistics
     * @returns {Promise<Object>} Event statistics
     */
    async getEventStatistics(deviceId, timeRange = {}) {
        try {
            const events = await this.getFilteredEventLogs(deviceId, {
                startDate: timeRange.startDate,
                endDate: timeRange.endDate,
                maxEvents: 10000
            });

            const stats = {
                deviceId,
                totalEvents: events.length,
                eventsByType: {},
                eventsBySeverity: {},
                authenticationEvents: {
                    total: 0,
                    successful: 0,
                    failed: 0,
                    successRate: 0
                },
                doorEvents: {
                    total: 0,
                    opened: 0,
                    closed: 0,
                    forcedOpen: 0,
                    alarms: 0,
                    emergencyLocks: 0
                },
                attendanceEvents: {
                    total: 0,
                    checkIn: 0,
                    checkOut: 0,
                    breakStart: 0,
                    breakEnd: 0,
                    tnaKeys: 0,
                    uniqueUsers: new Set()
                },
                timeRange: timeRange,
                generatedAt: new Date().toISOString()
            };

            // Process events for statistics
            events.forEach(event => {
                // Count by type
                stats.eventsByType[event.eventType] = (stats.eventsByType[event.eventType] || 0) + 1;
                
                // Count by severity
                stats.eventsBySeverity[event.severity] = (stats.eventsBySeverity[event.severity] || 0) + 1;
                
                // Authentication statistics
                if (event.eventType === 'authentication') {
                    stats.authenticationEvents.total++;
                    if ([0x1000, 0x1100, 0x1200, 0x1300, 0x1400, 0x1500, 0x1600, 0x1700].includes(event.eventcode)) {
                        stats.authenticationEvents.successful++;
                    } else {
                        stats.authenticationEvents.failed++;
                    }
                }
                
                // Door statistics
                if (event.eventType === 'door') {
                    stats.doorEvents.total++;
                    if (event.eventcode === 0x2000)      stats.doorEvents.opened++;
                    else if (event.eventcode === 0x2001) stats.doorEvents.closed++;
                    else if (event.eventcode === 0x2004) stats.doorEvents.forcedOpen++;
                    else if (event.eventcode === 0x2006 || event.eventcode === 0x2007) stats.doorEvents.alarms++;
                    else if (event.eventcode === 0x2200) stats.doorEvents.emergencyLocks++;
                }
                
                // Attendance statistics
                if (event.eventType === 'attendance') {
                    stats.attendanceEvents.total++;
                    if (event.eventcode === 0x6000)      stats.attendanceEvents.checkIn++;
                    else if (event.eventcode === 0x6001) stats.attendanceEvents.checkOut++;
                    else if (event.eventcode === 0x6002) stats.attendanceEvents.breakStart++;
                    else if (event.eventcode === 0x6003) stats.attendanceEvents.breakEnd++;
                    else if (event.eventcode >= 0x6100 && event.eventcode <= 0x610F) stats.attendanceEvents.tnaKeys++;
                    if (event.userid) {
                        stats.attendanceEvents.uniqueUsers.add(event.userid);
                    }
                }
            });

            // Calculate success rate
            if (stats.authenticationEvents.total > 0) {
                stats.authenticationEvents.successRate = 
                    (stats.authenticationEvents.successful / stats.authenticationEvents.total * 100).toFixed(2);
            }

            // Convert Set to count
            stats.attendanceEvents.uniqueUsers = stats.attendanceEvents.uniqueUsers.size;

            return stats;
        } catch (error) {
            this.logger.error('Error getting event statistics:', error);
            throw error;
        }
    }

    /**
     * Save image from image event
     * @param {Object} imageEvent - Image event object
     * @param {string} outputPath - Output path for image file
     * @returns {Promise<string>} Saved file path
     */
    async saveEventImage(imageEvent, outputPath) {
        try {
            if (!imageEvent.jpgimage) {
                throw new Error('No image data in event');
            }

            const imageBuffer = Buffer.from(imageEvent.jpgimage, 'base64');
            const fileName = `event_${imageEvent.id}_${Date.now()}.jpg`;
            const fullPath = path.join(outputPath, fileName);

            // Ensure directory exists
            if (!fs.existsSync(outputPath)) {
                fs.mkdirSync(outputPath, { recursive: true });
            }

            fs.writeFileSync(fullPath, imageBuffer);
            
            this.logger.info(`Saved event image to ${fullPath}`);
            return fullPath;
        } catch (error) {
            this.logger.error('Error saving event image:', error);
            throw error;
        }
    }

    // ================ UTILITY METHODS ================

    /**
     * Get monitoring status
     * @returns {Object} Monitoring status
     */
    getMonitoringStatus() {
        return {
            isMonitoring: this.isMonitoring,
            monitoredDevices: Array.from(this.eventSubscriptions.keys()),
            eventCodeMapSize: this.eventCodeMap.size
        };
    }

    /**
     * Export events to JSON file
     * @param {Array} events - Events to export
     * @param {string} filePath - Output file path
     * @returns {Promise<string>} Exported file path
     */
    async exportEvents(events, filePath) {
        try {
            const exportData = {
                exportedAt: new Date().toISOString(),
                eventCount: events.length,
                events: events
            };

            fs.writeFileSync(filePath, JSON.stringify(exportData, null, 2));
            
            this.logger.info(`Exported ${events.length} events to ${filePath}`);
            return filePath;
        } catch (error) {
            this.logger.error('Error exporting events:', error);
            throw error;
        }
    }
}

export default SupremaEventService;


